In [1]:
import pandas as pd
import numpy as np

In [2]:
base_dataset = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\hospital_cms_census_bls_rucc.csv")
base_dataset.head()

,year,state_code,provider_type,ccn_facility_type,number_of_beds,total_bed_days_available,occupancy_rate,total_discharges__v___xviii___xix___unknown_,total_days__v___xviii___xix___unknown_,fte___employees_on_payroll,...,population,median_age,median_income,poverty_rate,higher_education_rate,Other,wage_physician,wage_practitioner,wage_rn,wage_support
0,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,NaN,NaN,NaN,NaN,NaN,53754.888134,200193.678647,78568.610526,57840.0,25776.710446
1,2011,MT,General Short-Term (includes CAH),Critical Access Hospital,25.0,9125.0,0.131068,155.0,1196.0,70.56,...,NaN,NaN,NaN,NaN,NaN,53324.679487,181134.576271,68750.470914,60190.0,27864.492140
2,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,46.0,16790.0,0.159678,892.0,2681.0,72.65,...,NaN,NaN,NaN,NaN,NaN,53754.888134,200193.678647,78568.610526,57840.0,25776.710446
3,2011,AL,Rehabilitation Hospital,Rehabilitation Hospital,100.0,36500.0,0.887068,2390.0,32378.0,297.77,...,NaN,NaN,NaN,NaN,NaN,53754.888134,200193.678647,78568.610526,57840.0,25776.710446
4,2011,FL,Rehabilitation Hospital,Rehabilitation Hospital,70.0,25550.0,0.663836,1370.0,16961.0,154.60,...,NaN,NaN,NaN,NaN,NaN,61780.959858,186447.328473,78132.768107,64020.0,28961.926688

In [3]:
base_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75870 entries, 0 to 75869
Data columns (total 56 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   year                                          75870 non-null  int64
 1   state_code                                    75870 non-null  object
 2   provider_type                                 75870 non-null  object
 3   ccn_facility_type                             75870 non-null  object
 4   number_of_beds                                75870 non-null  float64
 5   total_bed_days_available                      75870 non-null  float64
 6   occupancy_rate                                75870 non-null  float64
 7   total_discharges__v___xviii___xix___unknown_  75870 non-null  float64
 8   total_days__v___xviii___xix___unknown_        75870 non-null  float64
 9   fte___employees_on_payroll                    75870 non-null  float64
 10  net_patient_revenue                           75870 non-null  float64
 11  total_income                                  75870 non-null  float64
 12  net_income                                    75870 non-null  float64
 13  total_costs                                   75870 non-null  float64
 14  total_other_expenses                          75870 non-null  float64
 15  total_assets                                  75870 non-null  float64
 16  total_liabilities                             75870 non-null  float64
 17  total_current_assets                          75870 non-null  float64
 18  total_current_liabilities                     75870 non-null  float64
 19  cash_on_hand_and_in_banks                     75870 non-null  float64
 20  accounts_receivable                           75870 non-null  float64
 21  accounts_payable                              75870 non-null  float64
 22  profit_margin_calc                            75870 non-null  float64
 23  cost_to_charge_ratio                          75870 non-null  float64
 24  charity_care_ratio                            75870 non-null  float64
 25  cost_of_charity_care                          75870 non-null  float64
 26  total_unreimbursed_and_uncompensated_care     75870 non-null  float64
 27  hospital_name                                 75870 non-null  object
 28  city                                          75870 non-null  object
 29  county                                        75870 non-null  object
 30  zip_code                                      75870 non-null  int64
 31  medicare_cbsa_number                          75870 non-null  float64
 32  type_of_control                               75870 non-null  object
 33  state_full_name                               75870 non-null  object
 34  expense_ratio                                 75870 non-null  float64
 35  current_ratio                                 75870 non-null  float64
 36  debt_to_asset_ratio                           75870 non-null  float64
 37  revenue_per_bed                               75870 non-null  float64
 38  staff_to_bed_ratio                            75870 non-null  float64
 39  discharges_per_bed                            75870 non-null  float64
 40  avg_length_of_stay                            75870 non-null  float64
 41  uncompensated_care_percent                    75870 non-null  float64
 42  charity_care_percent                          75870 non-null  float64
 43  rucc_code                                     69348 non-null  float64
 44  rural_urban                                   69348 non-null  object
 45  fips                                          69348 non-null  float64
 46  population                                    63401 non-null  float64
 47  median_age                                    63401 non-null  float64
 48  median_income                                 63400 non-null  float64
 49  poverty_rate                                  63400 non-null  float64
 50  higher_education_rate                         63401 non-null  float64
 51  Other                                         69588 non-null  float64
 52  wage_physician                                69585 non-null  float64
 53  wage_practitioner                             69592 non-null  float64
 54  wage_rn                                       69590 non-null  float64
 55  wage_support                                  69592 non-null  float64
dtypes: float64(45), int64(2), object(9)
memory usage: 32.4+ MB

##### Column Dropping Framework  

Columns should only be dropped if they fall into one of these categories:  

Identifiers (non-generalizable)  

Target Leakage Variables  

Redundant Derived Variables  

High Multicollinearity Components  

Non-Analytical Administrative Fields  

Structural Missingness / Data Quality Issues

In [5]:
base_dataset.columns.tolist()

['year',
 'state_code',
 'provider_type',
 'ccn_facility_type',
 'number_of_beds',
 'total_bed_days_available',
 'occupancy_rate',
 'total_discharges__v___xviii___xix___unknown_',
 'total_days__v___xviii___xix___unknown_',
 'fte___employees_on_payroll',
 'net_patient_revenue',
 'total_income',
 'net_income',
 'total_costs',
 'total_other_expenses',
 'total_assets',
 'total_liabilities',
 'total_current_assets',
 'total_current_liabilities',
 'cash_on_hand_and_in_banks',
 'accounts_receivable',
 'accounts_payable',
 'profit_margin_calc',
 'cost_to_charge_ratio',
 'charity_care_ratio',
 'cost_of_charity_care',
 'total_unreimbursed_and_uncompensated_care',
 'hospital_name',
 'city',
 'county',
 'zip_code',
 'medicare_cbsa_number',
 'type_of_control',
 'state_full_name',
 'expense_ratio',
 'current_ratio',
 'debt_to_asset_ratio',
 'revenue_per_bed',
 'staff_to_bed_ratio',
 'discharges_per_bed',
 'avg_length_of_stay',
 'uncompensated_care_percent',
 'charity_care_percent',
 'rucc_code',
 'rural_urban',
 'fips',
 'population',
 'median_age',
 'median_income',
 'poverty_rate',
 'higher_education_rate',
 'Other',
 'wage_physician',
 'wage_practitioner',
 'wage_rn',
 'wage_support']

In [ ]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Copy dataset
ml_dataset = base_dataset.copy()

# STEP 1: Drop identifier columns
ml_dataset.drop(columns=[
    'hospital_name',      # Hospital name is identifier
    'city',               # City is identifier
    'county',             # County is identifier
    'zip_code',           # Zip code is identifier
    'state_full_name'     # Duplicate of state_code
], inplace=True)


# STEP 2: Census variables start from 2012, so filter out earlier years
ml_dataset = ml_dataset[ml_dataset['year'] >= 2012]   # Census variables start from 2012

# STEP 3: Separate numeric & categorical columns

numeric_cols = ml_dataset.select_dtypes(include=['float64','int64']).columns
cat_cols = ml_dataset.select_dtypes(include=['object']).columns

# STEP 4: Fill numeric missing values 
# We will use median imputation for numeric columns, which is robust to outliers.
num_imputer = SimpleImputer(strategy='median')  
ml_dataset[numeric_cols] = num_imputer.fit_transform(ml_dataset[numeric_cols])

# STEP 5: Fill categorical missing values

cat_imputer = SimpleImputer(strategy='most_frequent')
ml_dataset[cat_cols] = cat_imputer.fit_transform(ml_dataset[cat_cols])

# Convert 'year' to integer type
ml_dataset['year'] = ml_dataset['year'].astype(int)

# STEP 6: Save ML dataset
ml_dataset.to_csv("ml_dataset.csv", index=False)

print("ML dataset created successfully")
print("Shape:", ml_dataset.shape)

ML dataset created successfully
Shape: (69555, 51)

In [11]:
ml_dataset.head()

,year,state_code,provider_type,ccn_facility_type,number_of_beds,total_bed_days_available,occupancy_rate,total_discharges__v___xviii___xix___unknown_,total_days__v___xviii___xix___unknown_,fte___employees_on_payroll,...,population,median_age,median_income,poverty_rate,higher_education_rate,Other,wage_physician,wage_practitioner,wage_rn,wage_support
6315,2012,NY,General Short-Term (includes CAH),Short-Term Hospital,66.0,23424.0,0.519244,1659.0,11979.0,295.42,...,159788.0,38.6,53176.0,0.149096,0.261622,70712.748026,155368.326360,83726.706945,74100.0,29818.738535
6316,2012,IN,General Short-Term (includes CAH),Short-Term Hospital,66.0,23424.0,0.519244,1659.0,11979.0,295.42,...,159788.0,38.6,53176.0,0.149096,0.261622,61764.819949,185387.239336,78501.170093,57520.0,27585.759055
6317,2012,SC,Psychiatric Hospital,Psychiatric Hospital,66.0,23424.0,0.519244,1659.0,11979.0,295.42,...,159788.0,38.6,53176.0,0.149096,0.261622,65106.819338,170649.546742,79354.947692,58940.0,26791.394178
6318,2012,IN,Psychiatric Hospital,Psychiatric Hospital,66.0,23424.0,0.519244,1659.0,11979.0,295.42,...,159788.0,38.6,53176.0,0.149096,0.261622,61764.819949,185387.239336,78501.170093,57520.0,27585.759055
6319,2012,AL,General Short-Term (includes CAH),Short-Term Hospital,25.0,2196.0,0.147692,62.0,288.0,52.50,...,20730.0,40.3,30752.0,0.256854,0.128684,53952.464444,192390.248447,79807.847264,55270.0,24937.407102

In [12]:
ml_dataset.columns.tolist()

['year',
 'state_code',
 'provider_type',
 'ccn_facility_type',
 'number_of_beds',
 'total_bed_days_available',
 'occupancy_rate',
 'total_discharges__v___xviii___xix___unknown_',
 'total_days__v___xviii___xix___unknown_',
 'fte___employees_on_payroll',
 'net_patient_revenue',
 'total_income',
 'net_income',
 'total_costs',
 'total_other_expenses',
 'total_assets',
 'total_liabilities',
 'total_current_assets',
 'total_current_liabilities',
 'cash_on_hand_and_in_banks',
 'accounts_receivable',
 'accounts_payable',
 'profit_margin_calc',
 'cost_to_charge_ratio',
 'charity_care_ratio',
 'cost_of_charity_care',
 'total_unreimbursed_and_uncompensated_care',
 'medicare_cbsa_number',
 'type_of_control',
 'expense_ratio',
 'current_ratio',
 'debt_to_asset_ratio',
 'revenue_per_bed',
 'staff_to_bed_ratio',
 'discharges_per_bed',
 'avg_length_of_stay',
 'uncompensated_care_percent',
 'charity_care_percent',
 'rucc_code',
 'rural_urban',
 'fips',
 'population',
 'median_age',
 'median_income',
 'poverty_rate',
 'higher_education_rate',
 'Other',
 'wage_physician',
 'wage_practitioner',
 'wage_rn',
 'wage_support']

In [13]:
ml_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69555 entries, 6315 to 75869
Data columns (total 51 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   year                                          69555 non-null  int64
 1   state_code                                    69555 non-null  object
 2   provider_type                                 69555 non-null  object
 3   ccn_facility_type                             69555 non-null  object
 4   number_of_beds                                69555 non-null  float64
 5   total_bed_days_available                      69555 non-null  float64
 6   occupancy_rate                                69555 non-null  float64
 7   total_discharges__v___xviii___xix___unknown_  69555 non-null  float64
 8   total_days__v___xviii___xix___unknown_        69555 non-null  float64
 9   fte___employees_on_payroll                    69555 non-null  float64
 10  net_patient_revenue                           69555 non-null  float64
 11  total_income                                  69555 non-null  float64
 12  net_income                                    69555 non-null  float64
 13  total_costs                                   69555 non-null  float64
 14  total_other_expenses                          69555 non-null  float64
 15  total_assets                                  69555 non-null  float64
 16  total_liabilities                             69555 non-null  float64
 17  total_current_assets                          69555 non-null  float64
 18  total_current_liabilities                     69555 non-null  float64
 19  cash_on_hand_and_in_banks                     69555 non-null  float64
 20  accounts_receivable                           69555 non-null  float64
 21  accounts_payable                              69555 non-null  float64
 22  profit_margin_calc                            69555 non-null  float64
 23  cost_to_charge_ratio                          69555 non-null  float64
 24  charity_care_ratio                            69555 non-null  float64
 25  cost_of_charity_care                          69555 non-null  float64
 26  total_unreimbursed_and_uncompensated_care     69555 non-null  float64
 27  medicare_cbsa_number                          69555 non-null  float64
 28  type_of_control                               69555 non-null  object
 29  expense_ratio                                 69555 non-null  float64
 30  current_ratio                                 69555 non-null  float64
 31  debt_to_asset_ratio                           69555 non-null  float64
 32  revenue_per_bed                               69555 non-null  float64
 33  staff_to_bed_ratio                            69555 non-null  float64
 34  discharges_per_bed                            69555 non-null  float64
 35  avg_length_of_stay                            69555 non-null  float64
 36  uncompensated_care_percent                    69555 non-null  float64
 37  charity_care_percent                          69555 non-null  float64
 38  rucc_code                                     69555 non-null  float64
 39  rural_urban                                   69555 non-null  object
 40  fips                                          69555 non-null  float64
 41  population                                    69555 non-null  float64
 42  median_age                                    69555 non-null  float64
 43  median_income                                 69555 non-null  float64
 44  poverty_rate                                  69555 non-null  float64
 45  higher_education_rate                         69555 non-null  float64
 46  Other                                         69555 non-null  float64
 47  wage_physician                                69555 non-null  float64
 48  wage_practitioner                             69555 non-null  float64
 49  wage_rn                                       69555 non-null  float64
 50  wage_support                                  69555 non-null  float64
dtypes: float64(45), int64(1), object(5)
memory usage: 27.6+ MB